---
- name: setup rustlang
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Check if 1password is installed
      shell: which 1password
      register: is_1password_installed_cmd
      failed_when: false
    - name: set if 1password is available
      set_fact:
        is_1password_installed: "{{is_1password_installed_cmd.stdout != ''}}"

    - name: download 1password package
      command : curl https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb -o /tmp/1password-latest.deb
      become: false
      args:
        creates: /tmp/1password-latest.deb
      when: not is_1password_installed
    - name: install 1password
      become: true
      apt:
        deb: /tmp/1password-latest.deb
      when: not is_1password_installed
