---
- name: install google chrome
  connection: local
  hosts: localhost
  become: true
  tasks:
    - name: add google's linux signing key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
    - name: add google's debian repository
      apt_repository:
        repo: deb https://dl.google.com/linux/chrome/deb/ stable main
        state: present
    - name: install chrome
      apt:
        name: google-chrome-stable
        state: latest
        update_cache: yes
