---
- name: install common packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: install apt packages
      apt:
        pkg:
          - obs-studio
          - lm-sensors
          - vlc
          - steam
        state: latest
        update_cache: yes
    - name: install classic snaps
      community.general.snap:
        name:
          - slack
          - gimp
          - gitkraken
        classic: yes
    - name: install snap apps
      community.general.snap:
        name:
          - discord
          - postman
          - insomnia
          - gh
