---
- name: setup ssh keys
  hosts: localhost
  connection: local
  roles:
    - {role: juju4.gpgkey_generate, gpg_user: "{{ ansible_user_id }}", gpg_generator_user: "{{ ansible_user_id }}", gpg_realname: "Nishchal Gautam", gpg_useremail: "gautam.nishchal@gmail.com"}
  post_tasks:
    - name: Read SSH public key to authorize
      shell: cat ./tmp/{{ansible_user_id}}-fingerprint
      register: ssh_pub_key
    - name: export public key
      shell: gpg --armor --export "{{ ssh_pub_key.stdout_lines[0] }}"
      register: gpg_key
    - name: display public key
      copy:
        dest: /tmp/pub.pub
        content: "{{gpg_key.stdout_lines | join('\n')}}"
